/* Generated By:JavaCC: Do not edit this line. Func1Parser.java */
package lf1.plp.functional1.parser;

// Imports da LF1 original
import lf1.plp.functional1.*;
import lf1.plp.functional1.declaration.DecVariavel;
import lf1.plp.functional1.declaration.DeclaracaoFuncional;
import lf1.plp.functional1.declaration.DecFuncao;
import lf1.plp.functional1.declaration.DecComposta;
import lf1.plp.functional1.expression.ExpDeclaracao;
import lf1.plp.functional1.expression.IfThenElse;
import lf1.plp.functional1.expression.Aplicacao;
import java.util.*;
import lf1.plp.expressions2.expression.ExpAnd;
import lf1.plp.expressions2.expression.ExpConcat;
import lf1.plp.expressions2.expression.ExpEquals;
import lf1.plp.expressions2.expression.ExpLength;
import lf1.plp.expressions2.expression.ExpMenos;
import lf1.plp.expressions2.expression.ExpNot;
import lf1.plp.expressions2.expression.ExpOr;
import lf1.plp.expressions2.expression.ExpSoma;
import lf1.plp.expressions2.expression.ExpSub;
import lf1.plp.expressions2.expression.Expressao;
import lf1.plp.expressions2.expression.Id;
import lf1.plp.expressions2.expression.Valor;
import lf1.plp.expressions2.expression.ValorBooleano;
import lf1.plp.expressions2.expression.ValorInteiro;
import lf1.plp.expressions2.expression.ValorString;

// --- ADICIONADO: Imports para as novas classes de Conjunto ---
import lf1.plp.functional1.expression.set.ExpLiteralSet;
import lf1.plp.functional1.expression.set.ExpRange;
import lf1.plp.functional1.expression.set.ExpMap;
import lf1.plp.functional1.expression.set.ExpFilter;
import lf1.plp.functional1.expression.set.ExpUniao;
import lf1.plp.functional1.expression.set.ExpIntersecao;
import lf1.plp.functional1.expression.set.ExpDiferenca;
import lf1.plp.functional1.expression.set.ExpIn;
import lf1.plp.functional1.expression.set.ExpSubset;
import lf1.plp.functional1.expression.set.ExpCardinalidade;
import lf1.plp.functional1.expression.set.ExpUniaoDistribuida;
import lf1.plp.functional1.expression.set.ExpIntersecaoDistribuida;
import lf1.plp.functional1.expression.set.ValorConjunto; // Import para o main
// --- FIM DOS IMPORTS ADICIONADOS ---

public class Func1Parser implements Func1ParserConstants {
  // ... (main original modificado para SetExpr) ...
  public static void main(String args [])
  {
    Func1Parser parser;
    if (args.length == 0)
    {
      System.out.println("SetExpr PLP Parser Version 0.0.1:  Reading from standard input . . .");
      parser = new Func1Parser(System.in);
    }
    else if (args.length == 1)
    {
      System.out.println("SetExpr PLP Parser Version 0.0.1:  Reading from file " + args [0] + " . . .");
      try
      {
        parser = new Func1Parser(new java.io.FileInputStream(args [0]));
      }
      catch (java.io.FileNotFoundException e)
      {
        System.out.println("SetExpr PLP Parser Version 0.0.1:  File " + args [0] + " not found.");
        return;
      }
    }
    else
    {
      System.out.println("SetExpr PLP Parser Version 0.0.1:  Usage is one of:");
      System.out.println("         java Func1Parser < inputfile");
      System.out.println("OR");
      System.out.println("         java Func1Parser inputfile");
      return;
    }
    Programa programa = null;
    try
    {
      programa = parser.Input();
      if (!programa.checaTipo())
          {
            System.out.println("SetExpr PLP Parser Version 0.0.1: Erro de tipo.");
        System.exit(0);
      }
      System.out.println("SetExpr PLP Parser Version 0.0.1: SetExpr program parsed successfully.");
    }
    catch (ParseException e)
    {
      e.printStackTrace();
      System.out.println("SetExpr PLP Parser Version 0.0.1: Encountered errors during parse.");
      System.exit(0);
    }
    try
    {
      System.out.println("SetExpr PLP Parser Version 0.0.1: running...");
      Valor val = programa.executar();

      // --- ADICIONADO: Suporte para imprimir ValorConjunto ---
      if (val instanceof lf1.plp.functional1.expression.set.ValorConjunto)
      {
        System.out.println("SetExpr PLP Parser Version 0.0.1: resultado=" + val);
      }
      // --- FIM DA ADIÇÃO ---
      else if (val instanceof ValorString)
      {
        ValorString valStr = (ValorString) val;
        System.out.println("SetExpr PLP Parser Version 0.0.1: resultado=" + valStr.valor());
      }
      else if (val instanceof ValorInteiro)
      {
        ValorInteiro valInt = (ValorInteiro) val;
        System.out.println("SetExpr PLP Parser Version 0.0.1: resultado=" + valInt.valor());
      }
      else if (val instanceof ValorBooleano)
      {
        ValorBooleano valBool = (ValorBooleano) val;
        System.out.println("SetExpr PLP Parser Version 0.0.1: resultado=" + valBool.valor());
      }
      else
      {
        System.out.println("SetExpr PLP Parser Version 0.0.1: resultado=" + val);
      }
    }
    catch (Exception e)
    {
      e.printStackTrace();
      System.out.println("SetExpr PLP Parser Version 0.0.1:  Encountered errors during execution.");
    }
  }

  final public Programa Input() throws ParseException {
  Programa retorno;
    retorno = PPrograma();
    jj_consume_token(0);
    {if (true) return retorno;}
    throw new Error("Missing return statement in function");
  }

// ... (PValorInteiro, PValorBooleano, PValorString, PValor, PId permanecem os mesmos) ...
  final public Valor PValorInteiro() throws ParseException {
                          Token token;
    token = jj_consume_token(INTEGER_LITERAL);
                                                                       {if (true) return new ValorInteiro(Integer.parseInt(token.toString()));}
    throw new Error("Missing return statement in function");
  }

  final public Valor PValorBooleano() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case FALSE:
      jj_consume_token(FALSE);
                                        {if (true) return new ValorBooleano(false);}
      break;
    case TRUE:
      jj_consume_token(TRUE);
                                                                                      {if (true) return new ValorBooleano(true);}
      break;
    default:
      jj_la1[0] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Valor PValorString() throws ParseException {
                         Token token;
    token = jj_consume_token(STRING_LITERAL);
                                                                     String tokenStr = token.toString(); tokenStr = tokenStr.substring(1, tokenStr.length() - 1); {if (true) return new ValorString(tokenStr);}
    throw new Error("Missing return statement in function");
  }

  final public Valor PValor() throws ParseException {
                   Valor retorno;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INTEGER_LITERAL:
      retorno = PValorInteiro();
      break;
    case TRUE:
    case FALSE:
      retorno = PValorBooleano();
      break;
    case STRING_LITERAL:
      retorno = PValorString();
      break;
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                                                                                                                              {if (true) return retorno;}
    throw new Error("Missing return statement in function");
  }

  final public Id PId() throws ParseException {
             Token token;
    token = jj_consume_token(IDENTIFIER);
                                                     String tokenStr = token.toString(); {if (true) return new Id(tokenStr);}
    throw new Error("Missing return statement in function");
  }

// ... (PExpMenos, PExpNot, PExpLength permanecem os mesmos) ...
  final public Expressao PExpMenos() throws ParseException {
                          Expressao retorno;
    jj_consume_token(MINUS);
    retorno = PExpPrimaria();
                                                                                    {if (true) return new ExpMenos(retorno);}
    throw new Error("Missing return statement in function");
  }

  final public Expressao PExpNot() throws ParseException {
                        Expressao retorno;
    jj_consume_token(NOT);
    retorno = PExpPrimaria();
                                                                                {if (true) return new ExpNot(retorno);}
    throw new Error("Missing return statement in function");
  }

  final public Expressao PExpLength() throws ParseException {
                           Expressao retorno;
    jj_consume_token(LENGTH);
    retorno = PExpPrimaria();
                                                                                      {if (true) return new ExpLength(retorno);}
    throw new Error("Missing return statement in function");
  }

// --- ADICIONADO: Regras unárias de Conjunto ---
  final public Expressao PExpCardinalidade() throws ParseException {
                                  Expressao retorno;
    jj_consume_token(NUMBER);
    retorno = PExpPrimaria();
                                                                                             {if (true) return new ExpCardinalidade(retorno);}
    throw new Error("Missing return statement in function");
  }

  final public Expressao PExpUniaoDistribuida() throws ParseException {
                                     Expressao retorno;
    jj_consume_token(D_UNION);
    retorno = PExpPrimaria();
                                                                                                 {if (true) return new ExpUniaoDistribuida(retorno);}
    throw new Error("Missing return statement in function");
  }

  final public Expressao PExpIntersecaoDistribuida() throws ParseException {
                                          Expressao retorno;
    jj_consume_token(D_INTER);
    retorno = PExpPrimaria();
                                                                                                      {if (true) return new ExpIntersecaoDistribuida(retorno);}
    throw new Error("Missing return statement in function");
  }

// --- FIM DAS ADIÇÕES ---
  final public Expressao PExpPrimaria() throws ParseException {
  Expressao retorno;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TRUE:
    case FALSE:
    case INTEGER_LITERAL:
    case STRING_LITERAL:
      retorno = PValor();
      break;
    case IDENTIFIER:
      retorno = PId();
      break;
    case LBRACE:
      jj_consume_token(LBRACE);
      retorno = PConjunto();
      break;
    case LPAREN:
      jj_consume_token(LPAREN);
      retorno = PExpressao();
      jj_consume_token(RPAREN);
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    {if (true) return retorno;}
    throw new Error("Missing return statement in function");
  }

// --- ADICIONADO: Funções auxiliares para Conjuntos ---
// (PRange foi removido daqui e substituído por PExpRange na hierarquia)

// Função para tratar tudo que começa com {
  final public Expressao PConjunto() throws ParseException {
  Expressao e1, e2;
  Id id;
  List<Expressao> elems;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case RBRACE:
      jj_consume_token(RBRACE);
    {if (true) return new ExpLiteralSet(new ArrayList<Expressao>());}
      break;
    default:
      jj_la1[3] = jj_gen;
      if (jj_2_1(2147483647)) {
        // Caso 2: Map {x*x : x in S}
          e1 = PExpressao();
        jj_consume_token(COLON);
        id = PId();
        jj_consume_token(IN);
        e2 = PExpressao();
        jj_consume_token(RBRACE);
    {if (true) return new ExpMap(e1, id, e2);}
      } else if (jj_2_2(2147483647)) {
        // Caso 3: Filter {x in S : x > 2}
          id = PId();
        jj_consume_token(IN);
        e1 = PExpressao();
        jj_consume_token(COLON);
        e2 = PExpressao();
        jj_consume_token(RBRACE);
    {if (true) return new ExpFilter(id, e1, e2);}
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case NOT:
        case LENGTH:
        case TRUE:
        case FALSE:
        case LET:
        case IF:
        case NUMBER:
        case D_UNION:
        case D_INTER:
        case INTEGER_LITERAL:
        case STRING_LITERAL:
        case IDENTIFIER:
        case LPAREN:
        case LBRACE:
        case RBRACE:
        case MINUS:
          elems = PListaExp();
          jj_consume_token(RBRACE);
    {if (true) return new ExpLiteralSet(elems);}
          break;
        default:
          jj_la1[4] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    throw new Error("Missing return statement in function");
  }

// Função para analisar lista de expressões (para literais de conjunto e aplicação de função)
  final public List PListaExp() throws ParseException {
  List<Expressao> retorno = new ArrayList<Expressao>();
  Expressao e;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NOT:
    case LENGTH:
    case TRUE:
    case FALSE:
    case LET:
    case IF:
    case NUMBER:
    case D_UNION:
    case D_INTER:
    case INTEGER_LITERAL:
    case STRING_LITERAL:
    case IDENTIFIER:
    case LPAREN:
    case LBRACE:
    case MINUS:
      // --- MODIFICADO: Torna a lista de expressões opcional ---
          e = PExpressao();
                       retorno.add(e);
      label_1:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
          ;
          break;
        default:
          jj_la1[5] = jj_gen;
          break label_1;
        }
        jj_consume_token(COMMA);
        e = PExpressao();
                                 retorno.add(e);
      }
      break;
    default:
      jj_la1[6] = jj_gen;
      ;
    }
    {if (true) return retorno;}
    throw new Error("Missing return statement in function");
  }

// --- FIM DAS FUNÇÕES ADICIONADAS ---
  final public List PListaId() throws ParseException {
  List < Id > retorno = null;
  Id id;
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFIER:
        ;
        break;
      default:
        jj_la1[7] = jj_gen;
        break label_2;
      }
      id = PId();
      if (retorno == null)
      {
        retorno = new ArrayList < Id > ();
        retorno.add(id);
      }
      else
      {
        retorno.add(id);
      }
    }
    {if (true) return retorno;}
    throw new Error("Missing return statement in function");
  }

// ... (PDeclVar, PDeclFuncao, PDecComposta, PDeclFuncional, PExpDeclaracao, PExpCondicional permanecem os mesmos) ...
  final public DeclaracaoFuncional PDeclVar() throws ParseException {
                                   Id id; Expressao expressao; DeclaracaoFuncional retorno;
    jj_consume_token(VAR);
    id = PId();
    jj_consume_token(ASSIGN);
    expressao = PExpressao();
                                                                                                                                                         {if (true) return new DecVariavel(id, expressao);}
    throw new Error("Missing return statement in function");
  }

  final public DeclaracaoFuncional PDeclFuncao() throws ParseException {
                                      Id id; Expressao expressao; DeclaracaoFuncional retorno; List <Id> lista;
    jj_consume_token(FUNC);
    id = PId();
    lista = PListaId();
    jj_consume_token(ASSIGN);
    expressao = PExpressao();
                                                                                                                                                                                                 {if (true) return new DecFuncao(id, lista, expressao);}
    throw new Error("Missing return statement in function");
  }

  final public DecComposta PDecComposta() throws ParseException {
                               DeclaracaoFuncional d1; DeclaracaoFuncional d2;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case VAR:
      d1 = PDeclVar();
      break;
    case FUNC:
      d1 = PDeclFuncao();
      break;
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(COMMA);
    d2 = PDeclFuncional();
                                                                                                                                                           {if (true) return new DecComposta(d1, d2);}
    throw new Error("Missing return statement in function");
  }

  final public DeclaracaoFuncional PDeclFuncional() throws ParseException {
                                         DeclaracaoFuncional decl;
    if (jj_2_3(2147483647)) {
      decl = PDecComposta();
    } else if (jj_2_4(2147483647)) {
      decl = PDecComposta();
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VAR:
        decl = PDeclVar();
        break;
      case FUNC:
        decl = PDeclFuncao();
        break;
      case LPAREN:
        jj_consume_token(LPAREN);
        decl = PDeclFuncional();
        jj_consume_token(RPAREN);
        break;
      default:
        jj_la1[9] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
                                                                                                                                                                                                                                                                                 {if (true) return decl;}
    throw new Error("Missing return statement in function");
  }

  final public Expressao PExpDeclaracao() throws ParseException {
                               DeclaracaoFuncional declaracoes; Expressao expressao;
    jj_consume_token(LET);
    declaracoes = PDeclFuncional();
    jj_consume_token(IN);
    expressao = PExpressao();
                                                                                                                                                              {if (true) return new ExpDeclaracao(declaracoes, expressao);}
    throw new Error("Missing return statement in function");
  }

  final public Expressao PExpCondicional() throws ParseException {
                                Expressao expCond, expThen, expElse;
    jj_consume_token(IF);
    expCond = PExpressao();
    jj_consume_token(THEN);
    expThen = PExpressao();
    jj_consume_token(ELSE);
    expElse = PExpressao();
                                                                                                                                                                   {if (true) return new IfThenElse(expCond, expThen, expElse);}
    throw new Error("Missing return statement in function");
  }

  final public Expressao PAplicacao() throws ParseException {
  List expressoes = null;
  Id id;
    id = PId();
    jj_consume_token(LPAREN);
    // --- MODIFICADO: para usar PListaExp (que agora suporta lista vazia) ---
        expressoes = PListaExp();
    jj_consume_token(RPAREN);
    {if (true) return new Aplicacao(id, expressoes);}
    throw new Error("Missing return statement in function");
  }

  final public Expressao PExpUnaria() throws ParseException {
  Expressao retorno;
    if (jj_2_5(2147483647)) {
      retorno = PExpMenos();
    } else if (jj_2_6(2147483647)) {
      retorno = PExpNot();
    } else if (jj_2_7(2147483647)) {
      retorno = PExpLength();
    } else if (jj_2_8(2147483647)) {
      retorno = PExpCardinalidade();
    } else if (jj_2_9(2147483647)) {
      retorno = PExpUniaoDistribuida();
    } else if (jj_2_10(2147483647)) {
      retorno = PExpIntersecaoDistribuida();
    } else if (jj_2_11(2147483647)) {
      retorno = PExpDeclaracao();
    } else if (jj_2_12(2147483647)) {
      retorno = PExpCondicional();
    } else if (jj_2_13(2147483647)) {
      retorno = PAplicacao();
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case TRUE:
      case FALSE:
      case INTEGER_LITERAL:
      case STRING_LITERAL:
      case IDENTIFIER:
      case LPAREN:
      case LBRACE:
        retorno = PExpRange();
        break;
      default:
        jj_la1[10] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    {if (true) return retorno;}
    throw new Error("Missing return statement in function");
  }

// --- ADICIONADO: Nova regra PExpRange para quebrar a recursão ---
  final public Expressao PExpRange() throws ParseException {
  Expressao e1, e2;
    e1 = PExpPrimaria();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case RANGE:
      jj_consume_token(RANGE);
      e2 = PExpPrimaria();
      {if (true) return new ExpRange(e1, e2);}
      break;
    default:
      jj_la1[11] = jj_gen;
      ;
    }
    {if (true) return e1;}
    throw new Error("Missing return statement in function");
  }

// --- FIM DA ADIÇÃO ---
  final public Expressao PExpBinaria() throws ParseException {
  Expressao retorno, param2;
    retorno = PExpBinaria2();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case EQ:
        ;
        break;
      default:
        jj_la1[12] = jj_gen;
        break label_3;
      }
      jj_consume_token(EQ);
      param2 = PExpBinaria2();
        retorno = new ExpEquals(retorno, param2);
    }
    {if (true) return retorno;}
    throw new Error("Missing return statement in function");
  }

  final public Expressao PExpBinaria2() throws ParseException {
  Expressao retorno, param2;
    retorno = PExpBinariaSet();
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OR:
      case CONCAT:
      case PLUS:
      case MINUS:
        ;
        break;
      default:
        jj_la1[13] = jj_gen;
        break label_4;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
        jj_consume_token(PLUS);
        param2 = PExpBinariaSet();
        retorno = new ExpSoma(retorno, param2);
        break;
      case MINUS:
        jj_consume_token(MINUS);
        param2 = PExpBinariaSet();
        retorno = new ExpSub(retorno, param2);
        break;
      case OR:
        jj_consume_token(OR);
        param2 = PExpBinariaSet();
        retorno = new ExpOr(retorno, param2);
        break;
      case CONCAT:
        jj_consume_token(CONCAT);
        param2 = PExpBinariaSet();
        retorno = new ExpConcat(retorno, param2);
        break;
      default:
        jj_la1[14] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    {if (true) return retorno;}
    throw new Error("Missing return statement in function");
  }

// --- ADICIONADO: Nova regra para operadores de conjunto binários ---
  final public Expressao PExpBinariaSet() throws ParseException {
  Expressao retorno, param2;
    retorno = PExpBinaria3();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IN:
      case UNION:
      case INTER:
      case DIFF:
      case SUBSET:
        ;
        break;
      default:
        jj_la1[15] = jj_gen;
        break label_5;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case UNION:
        jj_consume_token(UNION);
        param2 = PExpBinaria3();
        retorno = new ExpUniao(retorno, param2);
        break;
      case INTER:
        jj_consume_token(INTER);
        param2 = PExpBinaria3();
        retorno = new ExpIntersecao(retorno, param2);
        break;
      case DIFF:
        jj_consume_token(DIFF);
        param2 = PExpBinaria3();
        retorno = new ExpDiferenca(retorno, param2);
        break;
      case IN:
        jj_consume_token(IN);
        param2 = PExpBinaria3();
        retorno = new ExpIn(retorno, param2);
        break;
      case SUBSET:
        jj_consume_token(SUBSET);
        param2 = PExpBinaria3();
        retorno = new ExpSubset(retorno, param2);
        break;
      default:
        jj_la1[16] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    {if (true) return retorno;}
    throw new Error("Missing return statement in function");
  }

// --- FIM DA ADIÇÃO ---
  final public Expressao PExpBinaria3() throws ParseException {
  Expressao retorno, param2;
    retorno = PExpUnaria();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND:
        ;
        break;
      default:
        jj_la1[17] = jj_gen;
        break label_6;
      }
      jj_consume_token(AND);
      param2 = PExpUnaria();
        retorno = new ExpAnd(retorno, param2);
    }
    {if (true) return retorno;}
    throw new Error("Missing return statement in function");
  }

  final public Expressao PExpressao() throws ParseException {
  Expressao retorno;
    retorno = PExpBinaria();
    {if (true) return retorno;}
    throw new Error("Missing return statement in function");
  }

  final public Programa PPrograma() throws ParseException {
  Expressao retorno;
    retorno = PExpressao();
    {if (true) return new Programa(retorno);}
    throw new Error("Missing return statement in function");
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  private boolean jj_2_10(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  private boolean jj_2_11(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_11(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  private boolean jj_2_12(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_12(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  private boolean jj_2_13(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_13(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(12, xla); }
  }

  private boolean jj_3R_32() {
    if (jj_3R_8()) return true;
    return false;
  }

  private boolean jj_3R_48() {
    if (jj_3R_64()) return true;
    return false;
  }

  private boolean jj_3R_7() {
    if (jj_3R_19()) return true;
    return false;
  }

  private boolean jj_3R_25() {
    if (jj_3R_18()) return true;
    return false;
  }

  private boolean jj_3R_20() {
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_25()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_56() {
    if (jj_scan_token(AND)) return true;
    if (jj_3R_55()) return true;
    return false;
  }

  private boolean jj_3R_15() {
    if (jj_scan_token(D_INTER)) return true;
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3R_40() {
    if (jj_3R_55()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_56()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_81() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_7()) return true;
    return false;
  }

  private boolean jj_3R_77() {
    if (jj_scan_token(TRUE)) return true;
    return false;
  }

  private boolean jj_3R_78() {
    if (jj_3R_7()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_81()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_14() {
    if (jj_scan_token(D_UNION)) return true;
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3R_65() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_78()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_13() {
    if (jj_scan_token(NUMBER)) return true;
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3R_47() {
    if (jj_3R_63()) return true;
    return false;
  }

  private boolean jj_3_2() {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(IN)) return true;
    return false;
  }

  private boolean jj_3R_61() {
    if (jj_scan_token(SUBSET)) return true;
    if (jj_3R_40()) return true;
    return false;
  }

  private boolean jj_3R_60() {
    if (jj_scan_token(IN)) return true;
    if (jj_3R_40()) return true;
    return false;
  }

  private boolean jj_3_1() {
    if (jj_3R_7()) return true;
    if (jj_scan_token(COLON)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(IN)) return true;
    return false;
  }

  private boolean jj_3R_59() {
    if (jj_scan_token(DIFF)) return true;
    if (jj_3R_40()) return true;
    return false;
  }

  private boolean jj_3R_58() {
    if (jj_scan_token(INTER)) return true;
    if (jj_3R_40()) return true;
    return false;
  }

  private boolean jj_3R_52() {
    if (jj_3R_65()) return true;
    if (jj_scan_token(RBRACE)) return true;
    return false;
  }

  private boolean jj_3R_12() {
    if (jj_scan_token(LENGTH)) return true;
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3R_41() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_57()) {
    jj_scanpos = xsp;
    if (jj_3R_58()) {
    jj_scanpos = xsp;
    if (jj_3R_59()) {
    jj_scanpos = xsp;
    if (jj_3R_60()) {
    jj_scanpos = xsp;
    if (jj_3R_61()) return true;
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_57() {
    if (jj_scan_token(UNION)) return true;
    if (jj_3R_40()) return true;
    return false;
  }

  private boolean jj_3R_51() {
    if (jj_3R_18()) return true;
    if (jj_scan_token(IN)) return true;
    if (jj_3R_7()) return true;
    if (jj_scan_token(COLON)) return true;
    if (jj_3R_7()) return true;
    if (jj_scan_token(RBRACE)) return true;
    return false;
  }

  private boolean jj_3R_10() {
    if (jj_scan_token(MINUS)) return true;
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3R_11() {
    if (jj_scan_token(NOT)) return true;
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3_4() {
    if (jj_3R_9()) return true;
    if (jj_scan_token(COMMA)) return true;
    return false;
  }

  private boolean jj_3R_50() {
    if (jj_3R_7()) return true;
    if (jj_scan_token(COLON)) return true;
    if (jj_3R_18()) return true;
    if (jj_scan_token(IN)) return true;
    if (jj_3R_7()) return true;
    if (jj_scan_token(RBRACE)) return true;
    return false;
  }

  private boolean jj_3R_38() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_49()) {
    jj_scanpos = xsp;
    if (jj_3R_50()) {
    jj_scanpos = xsp;
    if (jj_3R_51()) {
    jj_scanpos = xsp;
    if (jj_3R_52()) return true;
    }
    }
    }
    return false;
  }

  private boolean jj_3R_49() {
    if (jj_scan_token(RBRACE)) return true;
    return false;
  }

  private boolean jj_3R_35() {
    if (jj_3R_40()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_41()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_31() {
    if (jj_3R_39()) return true;
    return false;
  }

  private boolean jj_3R_64() {
    if (jj_scan_token(STRING_LITERAL)) return true;
    return false;
  }

  private boolean jj_3R_46() {
    if (jj_3R_62()) return true;
    return false;
  }

  private boolean jj_3R_62() {
    if (jj_scan_token(INTEGER_LITERAL)) return true;
    return false;
  }

  private boolean jj_3R_37() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_46()) {
    jj_scanpos = xsp;
    if (jj_3R_47()) {
    jj_scanpos = xsp;
    if (jj_3R_48()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_45() {
    if (jj_scan_token(CONCAT)) return true;
    if (jj_3R_35()) return true;
    return false;
  }

  private boolean jj_3R_29() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_7()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3R_44() {
    if (jj_scan_token(OR)) return true;
    if (jj_3R_35()) return true;
    return false;
  }

  private boolean jj_3R_28() {
    if (jj_scan_token(LBRACE)) return true;
    if (jj_3R_38()) return true;
    return false;
  }

  private boolean jj_3R_18() {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_9() {
    if (jj_scan_token(FUNC)) return true;
    if (jj_3R_18()) return true;
    if (jj_3R_20()) return true;
    if (jj_scan_token(ASSIGN)) return true;
    if (jj_3R_7()) return true;
    return false;
  }

  private boolean jj_3R_43() {
    if (jj_scan_token(MINUS)) return true;
    if (jj_3R_35()) return true;
    return false;
  }

  private boolean jj_3R_76() {
    if (jj_scan_token(FALSE)) return true;
    return false;
  }

  private boolean jj_3R_27() {
    if (jj_3R_18()) return true;
    return false;
  }

  private boolean jj_3R_63() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_76()) {
    jj_scanpos = xsp;
    if (jj_3R_77()) return true;
    }
    return false;
  }

  private boolean jj_3R_26() {
    if (jj_3R_37()) return true;
    return false;
  }

  private boolean jj_3R_36() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_42()) {
    jj_scanpos = xsp;
    if (jj_3R_43()) {
    jj_scanpos = xsp;
    if (jj_3R_44()) {
    jj_scanpos = xsp;
    if (jj_3R_45()) return true;
    }
    }
    }
    return false;
  }

  private boolean jj_3R_42() {
    if (jj_scan_token(PLUS)) return true;
    if (jj_3R_35()) return true;
    return false;
  }

  private boolean jj_3R_21() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_26()) {
    jj_scanpos = xsp;
    if (jj_3R_27()) {
    jj_scanpos = xsp;
    if (jj_3R_28()) {
    jj_scanpos = xsp;
    if (jj_3R_29()) return true;
    }
    }
    }
    return false;
  }

  private boolean jj_3R_23() {
    if (jj_3R_35()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_36()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_54() {
    if (jj_3R_9()) return true;
    return false;
  }

  private boolean jj_3R_8() {
    if (jj_scan_token(VAR)) return true;
    if (jj_3R_18()) return true;
    if (jj_scan_token(ASSIGN)) return true;
    if (jj_3R_7()) return true;
    return false;
  }

  private boolean jj_3R_24() {
    if (jj_scan_token(EQ)) return true;
    if (jj_3R_23()) return true;
    return false;
  }

  private boolean jj_3R_16() {
    if (jj_scan_token(LET)) return true;
    if (jj_3R_22()) return true;
    if (jj_scan_token(IN)) return true;
    if (jj_3R_7()) return true;
    return false;
  }

  private boolean jj_3R_53() {
    if (jj_3R_8()) return true;
    return false;
  }

  private boolean jj_3R_19() {
    if (jj_3R_23()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_24()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_3() {
    if (jj_3R_8()) return true;
    if (jj_scan_token(COMMA)) return true;
    return false;
  }

  private boolean jj_3R_39() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_53()) {
    jj_scanpos = xsp;
    if (jj_3R_54()) return true;
    }
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3R_17() {
    if (jj_scan_token(IF)) return true;
    if (jj_3R_7()) return true;
    if (jj_scan_token(THEN)) return true;
    if (jj_3R_7()) return true;
    if (jj_scan_token(ELSE)) return true;
    if (jj_3R_7()) return true;
    return false;
  }

  private boolean jj_3R_30() {
    if (jj_3R_39()) return true;
    return false;
  }

  private boolean jj_3R_82() {
    if (jj_scan_token(RANGE)) return true;
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3R_22() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_30()) {
    jj_scanpos = xsp;
    if (jj_3R_31()) {
    jj_scanpos = xsp;
    if (jj_3R_32()) {
    jj_scanpos = xsp;
    if (jj_3R_33()) {
    jj_scanpos = xsp;
    if (jj_3R_34()) return true;
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_80() {
    if (jj_3R_21()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_82()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3_13() {
    if (jj_3R_18()) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  private boolean jj_3_12() {
    if (jj_3R_17()) return true;
    return false;
  }

  private boolean jj_3_11() {
    if (jj_3R_16()) return true;
    return false;
  }

  private boolean jj_3R_75() {
    if (jj_3R_80()) return true;
    return false;
  }

  private boolean jj_3_10() {
    if (jj_3R_15()) return true;
    return false;
  }

  private boolean jj_3R_74() {
    if (jj_3R_79()) return true;
    return false;
  }

  private boolean jj_3_9() {
    if (jj_3R_14()) return true;
    return false;
  }

  private boolean jj_3R_73() {
    if (jj_3R_17()) return true;
    return false;
  }

  private boolean jj_3_8() {
    if (jj_3R_13()) return true;
    return false;
  }

  private boolean jj_3R_72() {
    if (jj_3R_16()) return true;
    return false;
  }

  private boolean jj_3_7() {
    if (jj_3R_12()) return true;
    return false;
  }

  private boolean jj_3R_71() {
    if (jj_3R_15()) return true;
    return false;
  }

  private boolean jj_3_6() {
    if (jj_3R_11()) return true;
    return false;
  }

  private boolean jj_3R_70() {
    if (jj_3R_14()) return true;
    return false;
  }

  private boolean jj_3_5() {
    if (jj_3R_10()) return true;
    return false;
  }

  private boolean jj_3R_69() {
    if (jj_3R_13()) return true;
    return false;
  }

  private boolean jj_3R_68() {
    if (jj_3R_12()) return true;
    return false;
  }

  private boolean jj_3R_34() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_22()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3R_67() {
    if (jj_3R_11()) return true;
    return false;
  }

  private boolean jj_3R_66() {
    if (jj_3R_10()) return true;
    return false;
  }

  private boolean jj_3R_55() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_66()) {
    jj_scanpos = xsp;
    if (jj_3R_67()) {
    jj_scanpos = xsp;
    if (jj_3R_68()) {
    jj_scanpos = xsp;
    if (jj_3R_69()) {
    jj_scanpos = xsp;
    if (jj_3R_70()) {
    jj_scanpos = xsp;
    if (jj_3R_71()) {
    jj_scanpos = xsp;
    if (jj_3R_72()) {
    jj_scanpos = xsp;
    if (jj_3R_73()) {
    jj_scanpos = xsp;
    if (jj_3R_74()) {
    jj_scanpos = xsp;
    if (jj_3R_75()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_79() {
    if (jj_3R_18()) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_65()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3R_33() {
    if (jj_3R_9()) return true;
    return false;
  }

  /** Generated Token Manager. */
  public Func1ParserTokenManager token_source;
  JavaCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  /** Whether we are looking ahead. */
  private boolean jj_lookingAhead = false;
  private boolean jj_semLA;
  private int jj_gen;
  final private int[] jj_la1 = new int[18];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x6000,0x40006000,0x40006000,0x0,0x7404f800,0x0,0x7404f800,0x0,0x210000,0x210000,0x40006000,0x8000000,0x0,0x400,0x400,0x3c20000,0x3c20000,0x200,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x4,0x14c,0x200,0x4000034c,0x2000,0x4000014c,0x8,0x0,0x40,0x14c,0x0,0x400000,0x70000000,0x70000000,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[13];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public Func1Parser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Func1Parser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new JavaCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new Func1ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 18; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 18; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Func1Parser(java.io.Reader stream) {
    jj_input_stream = new JavaCharStream(stream, 1, 1);
    token_source = new Func1ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 18; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 18; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Func1Parser(Func1ParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 18; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(Func1ParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 18; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = jj_lookingAhead ? jj_scanpos : token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List jj_expentries = new java.util.ArrayList();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      boolean exists = false;
      for (java.util.Iterator it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          exists = true;
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              exists = false;
              break;
            }
          }
          if (exists) break;
        }
      }
      if (!exists) jj_expentries.add(jj_expentry);
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[69];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 18; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 69; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 13; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
            case 11: jj_3_12(); break;
            case 12: jj_3_13(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
